/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2022-01-24 06:04:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Login KFC</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("<style>\r\n");
      out.write(" \r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image:url(\"image/backround.jpg\");\r\n");
      out.write("\t\r\n");
      out.write("\tbackground-size: 1400px;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".container{\r\n");
      out.write("\tmargin-top:170px;\r\n");
      out.write("\tmarigin-botom:0px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("h2{\r\n");
      out.write("\tmargin-right:-90px; ;\r\n");
      out.write("\tmargin-top:50px;\r\n");
      out.write("}\r\n");
      out.write("label {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        width: 165px;\r\n");
      out.write("        font-color:yellow;\r\n");
      out.write("        text-align: right;\r\n");
      out.write("        margin-left:-40px; ;\r\n");
      out.write("      }\r\n");
      out.write("      button {\r\n");
      out.write("\tmargin-right:-80px; \r\n");
      out.write("}\r\n");
      out.write("a {\r\n");
      out.write("margin-right:-140px\r\n");
      out.write("}\r\n");
      out.write(".exception{\r\n");
      out.write("\tcolor:red;\r\n");
      out.write("\tbackround-color:white;\r\n");
      out.write("\tfont-size:15px;\r\n");
      out.write("\tfloat:center;\r\n");
      out.write("\tmargin-right:-150px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"login\" method=\"post\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<h2 align=\"center\"  >Login KFC</h2>\r\n");
      out.write("\t\t\t<label> <b>Mail ID:</label><input type=\"email\" name=\"mailId\" autofocus required placeholder=\"ex:kfc@gmail.com\"> <br> <br>\r\n");
      out.write("\t\t\t</label>Mobile Number:</label><input type=\"number\" name=\"mobileNumber\" required placeholder=\"Enter mobile Number\"> <br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-success btn-change7\">Login</button>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form> <br>\r\n");
      out.write("\t<br> if you don't have account?\r\n");
      out.write("\t<a  class=\"btn btn-primary\" href=\"Register.jsp\" >SignUp</a> <br> <br> <br>\r\n");
      out.write("\t\r\n");

   if(session.getAttribute("invalidUser") != null){
      out.write("\r\n");
      out.write("\t  <b> <h1 class=\"exception\"><i>Invalid MailId or Password</i></h1></b>\r\n");
      out.write("\t   \r\n");
      out.write("   ");
session.removeAttribute("invalidUser"); }
   
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
